spring.application.name=chap4

# Cau hinh ket noi SQL Server database HSF302_CH4
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH4;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=16052006
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cau hinh JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true